version: '{build}'

cache:
    - x86_64-4.9.2-release-win32-seh-rt_v4-rev4.7z
    - i686-4.9.2-release-win32-dwarf-rt_v4-rev4.7z
    - nim-0.19.0_x64.zip
    - nim-0.19.0_x32.zip

matrix:
    fast_finish: true

environment:
    matrix:
        - MINGW_DIR: mingw64
          MINGW_URL: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/4.9.2/threads-win32/seh/x86_64-4.9.2-release-win32-seh-rt_v4-rev4.7z/download
          MINGW_ARCHIVE: x86_64-4.9.2-release-win32-seh-rt_v4-rev4.7z
          NIM_ARCHIVE: nim-0.19.0_x64.zip
          NIM_DIR: nim-0.19.0
          NIM_URL: https://nim-lang.org/download/nim-0.19.0_x64.zip
          platform: x64

        - MINGW_DIR: mingw32
          MINGW_URL: https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/4.9.2/threads-win32/dwarf/i686-4.9.2-release-win32-dwarf-rt_v4-rev4.7z/download
          MINGW_ARCHIVE: i686-4.9.2-release-win32-dwarf-rt_v4-rev4.7z
          NIM_ARCHIVE: nim-0.19.0_x32zip
          NIM_DIR: nim-0.19.0
          NIM_URL: https://nim-lang.org/download/nim-0.19.0_x32.zip
          platform: x86

install:
    - MKDIR %CD%\tools_tmp
    - IF not exist "%MINGW_ARCHIVE%" appveyor DownloadFile "%MINGW_URL%" -FileName "%MINGW_ARCHIVE%"
    - 7z x -y "%MINGW_ARCHIVE%" -o"%CD%\tools_tmp"> nul
    - IF not exist "%NIM_ARCHIVE%" appveyor DownloadFile "%NIM_URL%" -FileName "%NIM_ARCHIVE%"
    - 7z x -y "%NIM_ARCHIVE%" -o"%CD%\tools_tmp"> nul
    - SET PATH=%CD%\tools_tmp\%NIM_DIR%\bin;%CD%\tools_tmp\%MINGW_DIR%\bin;%PATH%

build: off
deploy: off

test_script:
    - nimble.exe test
